import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { EdgeStoreProvider } from "@/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Specify the weights you need
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <ToastContainer position="top-center" hideProgressBar/>
        <div className="bg-slate-300 flex justify-center">
          <div className="bg-white w-full md:w-[420px] min-h-screen">
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
